### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#10]
@autumnfound   This should be the background image for the save the date site.

Date: Wednesday Sep 18th
Location: [Innovation Centre at Bayview Yards ](https://www.google.com/maps/place/7+Bayview+Station+Rd,+Ottawa,+ON+K1Y+3B5/@45.409686,-75.728026,16z/data=!4m5!3m4!1s0x4cce0441d4558e01:0x68c5b9a6731b105e!8m2!3d45.4096858!4d-75.7280263?hl=en-US)
![image](https://user-images.githubusercontent.com/2498391/61482237-2f7e2580-a968-11e9-946a-9c9a2ad073b4.png)
![image](https://user-images.githubusercontent.com/2498391/61482372-7409c100-a968-11e9-9a0e-17df5d2268cd.png)

_Originally posted by @rickoco in https://github.com/openhwgroup/osdforum.org/issues/2#issuecomment-512933765_

**Comment by autumnfound** [comment]
Which image? Also something to keep in mind, theres a lot of contrast in those images so text may be hard to read over those images without any changes.

**Comment by chrisguindon** [comment]
@stephanieswart could you please add your photoshop magic to these images so that we can use them in the header?

@rickoco which of the 2 images should we use? I assume it's the second one but I would like to make sure!

**Comment by stephanieswart** [comment]
![osdforumimages (1)](https://user-images.githubusercontent.com/34580334/61951848-37e5ea00-af80-11e9-8457-d0df76cbea8b.png)
![osdforumimages (2)](https://user-images.githubusercontent.com/34580334/61951850-39afad80-af80-11e9-97a6-006e3223ed7e.png)

Here you go!

**Comment by rickoco** [comment]
Thx @stephanieswart and @chrisguindon.

Yes please, the 7 Bayview Yards building picture for the background image in the header

**Comment by autumnfound** [comment]
This is live
