### ISSUE TITLE
'register now' text

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#12]
@autumnfound - the 'register now' text was meant to link to an eventbrite reg site (which is only now being setup by Anne in the Eclipse team. (can you sync with here / add her to this repo?)

So for now just show "Save the Date Sep 18th.  Agenda and registration details to follow."

**Comment by autumnfound** [comment]
I've been passed the eventbrite link, so I'll just add it now. Tickets aren't on sale yet, but people can be reminded for when they do go on sale.
