### ISSUE TITLE
Chrome & Safari on a Mac

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#13]
@autumnfound site rendenring issues / differences on Chrome & Safari on a Mac (screen shots below)

Chrome Screen Shot
![image](https://user-images.githubusercontent.com/2498391/61748450-3c3ab900-ad6e-11e9-9069-8e5d2050d97e.png)

Safari Screen Shot
![image](https://user-images.githubusercontent.com/2498391/61748497-5a081e00-ad6e-11e9-8c8d-3930988e200b.png)

**Comment by chrisguindon** [comment]
@rickoco did you try with a private window? I have a feeling that your browser is serving a cache version of the CSS.

**Comment by autumnfound** [comment]
I'm unable to reproduce in chromium, and I believe @chrisguindon has the right of it
