### ISSUE TITLE
Create a temporary save the date landing page

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/osdforum.org#2]
We need to create a save the date page ASAP.

@rickoco, please the content you would like to see on the site while we are working on it?

I presume you wish to include the following:

- logo
- Save The Date heading
- Event date and location
- Brief description of the event

**Comment by stephanieswart** [comment]
Here is the landing page placeholder
![osdforummockup_placeholderpage (1)](https://user-images.githubusercontent.com/34580334/61462630-eebee600-a940-11e9-893b-fa9738b957da.png)

**Comment by rickoco** [comment]
This looks great!  Can we also add a "Sponsored by" section where we'll have a bunch of logos (5 or 6 to start with on the 'save the date' page and more on the full site.

**Comment by stephanieswart** [comment]
How is this @rickoco?

![osdforummockup_placeholderpage (2)](https://user-images.githubusercontent.com/34580334/61480281-a1a03b80-a963-11e9-9d13-bd223706b4d8.png)

**Comment by rickoco** [comment]
Looks great!  Good to go.  Thank you @stephanieswart

**Comment by rickoco** [comment]
Date: Wednesday Sep 18th
Location: [Innovation Centre at Bayview Yards ](https://www.google.com/maps/place/7+Bayview+Station+Rd,+Ottawa,+ON+K1Y+3B5/@45.409686,-75.728026,16z/data=!4m5!3m4!1s0x4cce0441d4558e01:0x68c5b9a6731b105e!8m2!3d45.4096858!4d-75.7280263?hl=en-US)
![image](https://user-images.githubusercontent.com/2498391/61482237-2f7e2580-a968-11e9-946a-9c9a2ad073b4.png)
![image](https://user-images.githubusercontent.com/2498391/61482372-7409c100-a968-11e9-9a0e-17df5d2268cd.png)

**Comment by rickoco** [comment]
Text: The Open Source Developer Forum is a one day workshop that brings open source software and hardware (chips, boards and systems) developers together to collaborate and learn.  The agenda for the day will be published shortly and will include talks from leading industry and academic experts in the field of open source development and will also include a hands on bring up session of a RISC-V based development board that attendees can keep.  Made possible by the generous support of our sponsors, the OSDForum is a non-profit event with low attendee fees of $50 for industry attendees and $25 attendees (includes the full day of talks, breaks, lunch and a RISC-V development board).

**Registration is limited, so don't delay - register today!**

The OSDForum is co-hosted by the Eclipse Foundation, CMC Microsystem and the OpenHW Group.

**Comment by rickoco** [comment]
Sponsor logos to include so far:
![image](https://user-images.githubusercontent.com/2498391/61492288-074df100-a97f-11e9-9fb9-e31f81a21179.png)
![image](https://user-images.githubusercontent.com/2498391/61492338-1af95780-a97f-11e9-9e25-613c4437c7a3.png)
![image](https://user-images.githubusercontent.com/2498391/61492361-28aedd00-a97f-11e9-8f2d-aa789b140b9a.png)
![image](https://user-images.githubusercontent.com/2498391/61492458-52680400-a97f-11e9-915a-ad8490823ba8.png)
![image](https://user-images.githubusercontent.com/2498391/61492476-5d229900-a97f-11e9-80c5-856dd3eb4e06.png)

**Comment by chrisguindon** [comment]
The repository is ready for @autumnfound.

Martin, is currently working on high-priority task but I expect him to work on the save the date page on tuesday!

**Comment by rickoco** [comment]
Use the Bayview Yards building pic as the background image replacing the one in the mockup.

**Comment by rickoco** [comment]
I see this is up now https://www.osdforum.org/ but not branded as per the mockup.  Just confirming this is work in progress right?

**Comment by chrisguindon** [comment]
@rickoco Correct. As mentioned in mt previous comment on this thread. @autumnfound will start working on the save the date page tomorrow.

**Comment by rickoco** [comment]
Thank you @chrisguindon and @autumnfound

**Comment by autumnfound** [comment]
@rickoco I'm looking at developing the page now, and I need links for the sponsors. Most of them are pretty quick w/ a google search but it looks like CORE-V is project within OpenHW group. I've got it linked to https://www.openhwgroup.org/#core-v-family if you click on the sponsor image for now, is there something you would prefer?

**Comment by rickoco** [comment]
perfect @autumnfound - thank you

**Comment by autumnfound** [comment]
Also, do we have rights to post those images? We don't want to step on any toes. I'm guessing the logos are fine, but we just want to make sure we're cleared for these images.

**Comment by rickoco** [comment]
Yes - @autumnfound, the images were provide by Invest Ottawa...

**Comment by autumnfound** [comment]
Put a PR in, this should be live tomorrow morning:
![current state](https://user-images.githubusercontent.com/23018241/61735860-d7be3080-ad52-11e9-8ec7-757958296d8c.png)

**Comment by autumnfound** [comment]
This is live

**Comment by chrisguindon** [comment]
Thanks @autumnfound 

The remaining of the work will be done via #3
