### ISSUE TITLE
Temp logo

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#21]
@autumnfound - the site is looking good Martin.  While the OSDForum logo is being finalized, please change out the OSDForum text in the header with the attached temp logo (which is also used in the top left of the site).  Also, change out the OpenHW Group logo in the footer with this temp logo.

![image](https://user-images.githubusercontent.com/2498391/62138482-b2cb3f80-b2b5-11e9-9f9c-edb6d5233f93.png)

**Comment by chrisguindon** [comment]
@rickoco I have a feeling that the logo won't be easy to read in the header(orange + orange background).

Do you have a white logo that we could use there?

**Comment by rickoco** [comment]
actual logos will be ready soon, so hold off on this for now

**Comment by autumnfound** [comment]
@rickoco if we will just be implementing the actual logo (#5), we should just close this issue since we have an already open issue. Am I good to close this one?

**Comment by chrisguindon** [comment]
@autumnfound +1 We should use the existing logo bug for the new logo #5
