### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#25]
@autumnfound Please point the twitter social icon to https://twitter.com/osdforum

**Comment by chrisguindon** [comment]
Hi @rickoco,

You don't need to ask @autumnfound directly for making a change in a public github issue.

**Comment by chrisguindon** [comment]
I updated the link and twitter meta tags on the page to point to https://twitter.com/osdforum

The change should be live in the next 5 minutes! Please make sure to clear your cache before verifying the update!
