### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#27]
@autumnfound - pls update the site favicon with...

![image](https://user-images.githubusercontent.com/2498391/62301825-4a13cc80-b447-11e9-8322-55f50b7aeb55.png)

**Comment by rickoco** [comment]
here's a few other favicon sizes in case you need them...

![favicon-32x32](https://user-images.githubusercontent.com/2498391/62301983-8fd09500-b447-11e9-93d7-a6c5d027b116.png)
![favicon-96x96](https://user-images.githubusercontent.com/2498391/62301984-8fd09500-b447-11e9-9cbe-cbcbea96bbcd.png)

**Comment by autumnfound** [comment]
This is live
