### ISSUE TITLE
Create a template for osdforum

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/osdforum.org#3]
We will need to create a template for osdforum.org. It should be similar to https://events.eclipse.org/volttrondays/ without black background.

**Comment by chrisguindon** [comment]
@stephanieswart, could you create a mock up for this new site before we create the theme?

**Comment by rickoco** [comment]
don't think we actually need a mockup created.  To keep things simple, we can use the Voltron site as mockup as we'll need / want the exact same content and the layout is fine.  Just use the Eclipse orange and OpenHW blue as accent colors and a more traditional white background (and stock images) on https://jakartaone.org/ or https://www.eclipse.org/

**Comment by chrisguindon** [comment]
@rickoco the mockup is required to reduce back and forth feedback and development time for my team.

**Comment by rickoco** [comment]
ok - thx Chris.  Stephanie, let me know if you have any questions.  Looking to get this up asap so we can begin promotion and registration.

**Comment by stephanieswart** [comment]
Here is the mockup I've made for the full page (pending content, I can mock up other sections as necessary) 
![osdforummockup_full](https://user-images.githubusercontent.com/34580334/61462683-07c79700-a941-11e9-814a-e9d30f28a364.png)

**Comment by stephanieswart** [comment]
Full Mockup
![osdforummockup_full (3)](https://user-images.githubusercontent.com/34580334/61471616-08682980-a951-11e9-9e26-c360466ca05d.png)

**Comment by rickoco** [comment]
Thx Stephanie - we don't need the "Lodging" and "What's Around" sections.

We do need a sponsored by section.  

The event is only 1 day, so no "DAY 2" agenda.  We'll also what to show pop abstracts and speaker bios for each item on the agenda.  No need for "Room Location" (one track in one room).

**Comment by rickoco** [comment]
Also - all the privacy / terms of use links in the footer can point to the openhwgroup.org site.  Same with the copyright statement.

**Comment by stephanieswart** [comment]
@rickoco here is an updated version, let me know what you think
![osdforummockup_full (4)](https://user-images.githubusercontent.com/34580334/61478958-d232a600-a960-11e9-8099-97007a268636.png)

**Comment by stephanieswart** [comment]
@rickoco here is an updated version, let me know what you think
![osdforummockup_full (5)](https://user-images.githubusercontent.com/34580334/61479074-0908bc00-a961-11e9-92ed-7505b4d23cc4.png)

**Comment by stephanieswart** [comment]
For the webdev team - images used in mockup
[osdforumimages.zip](https://github.com/openhwgroup/osdforum.org/files/3407900/osdforumimages.zip)

**Comment by autumnfound** [comment]
@rickoco do you have content for the home page? I'm looking at working on that today and have set a general timeline of being done the layout by EOD

**Comment by rickoco** [comment]
@autumnfound its the same content as the save the date page for now - just with the agenda section populated with "to be announced"

**Comment by autumnfound** [comment]
What about the venue, or about sections? What should we link the register button to, the openHW group homepage?

**Comment by rickoco** [comment]
venue is as per save the date site [INNOVATION CENTRE AT BAYVIEW YARDS ](https://bayviewyards.org/)

About should have the lead in text from the save the date site.

**Comment by autumnfound** [comment]
The venue section with just the address is pretty empty. Do we have any little spiel about the facility we can use to help fill the space?
![venue section preview](https://user-images.githubusercontent.com/23018241/61799847-db58c280-adf9-11e9-9007-b8049e42156f.png)

**Comment by stephanieswart** [comment]
Here is a blurb about the space: 

Bayview Yards is a dynamic and energized hub that serves as basecamp for some of our greatest homegrown technology talent, capabilities and companies. It is the ultimate one-stop business acceleration shop and ‘mash-up’ of technical, business and market services, resources and expertise that helps entrepreneurs and companies launch, grow and thrive, and compete with anyone in the world.

**Comment by autumnfound** [comment]
The initial template has been put live. If there are any further enhancements needed, please create a new bug.
