### ISSUE TITLE
Center and add more spacing between the sponsor logos 

### ISSUE THREAD

**Issue by stephanieswart** [openhwgroup/osdforum.org#31]
@rickoco I'd like to make a suggestion with your blessing, I was talking to @autumnfound and thought the title 'Sponsored By' should be centered in the middle and the logos should have
![image (2)](https://user-images.githubusercontent.com/34580334/62317932-b226da80-b468-11e9-8a2d-e16e3c04cde9.png)
 a little more breathing room. WDYT?

Image attached

**Comment by rickoco** [comment]
Perfect!

________________________________

**Comment by rickoco** [comment]
@stephanieswart @autumnfound -  feel free to suggest these types of improvements anytime. You guys are the pros!  I'm just a hack :-)

**Comment by autumnfound** [comment]
This is live!
