### ISSUE TITLE
Updated About text

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#32]
@autumnfound - pls change the About text to...

About OSDForum
The Open Source Developer Forum is a one workshop that brings open source SW and HW (chips, boards and systems) developers together to collaborate and learn. The OSDForum includes talks from leading industry and academic experts focused on IoT, Edge and Machine Learning development leveraging open source SW and HW building blocks.  The agenda also includes a hands on bring up session using a RISC-V based development board that attendees can keep. Made possible by the generous support of our sponsors, the OSDForum is a non-profit event with low attendee fees of $50 for industry attendees and $25 for academic attendees (includes the full day of talks, breaks, lunch and a RISC-V development board).

Registration is limited, so don't delay - register today!

The OSDForum is co-hosted by CMC Microsystems, the Eclipse Foundation and the OpenHW Group.

**Comment by autumnfound** [comment]
@rickoco I've updated the text, but kept the link on `register today!`, as seen below in a snap from development:
![image](https://user-images.githubusercontent.com/23018241/62383480-e0b2bd00-b51d-11e9-9ef5-49a2dc2724a0.png)
I'll push this to be reviewed, and advise once live.

**Comment by autumnfound** [comment]
This is live!

**Comment by rickoco** [comment]
3 more small updates here... 

1. please add the following link to existing text in About OSDForum [RISC-V based development board](https://open-isa.org/)

2. make 'orum' lower case in the title

3. replace crowd pic with the following board image and include image title "RISC-V dev board attendees will keep"

![image](https://user-images.githubusercontent.com/2498391/62494430-8590fc80-b7a1-11e9-8d5c-f24cca9f4314.png)

**Comment by autumnfound** [comment]
1. Can do!
2. That breaks the design for headers as they are all currently upper case. Did you want to look at changing this?
3. Added, and optimized for web.

These changes are live, in current state. We can look at changing heading casing as a separate bug

**Comment by rickoco** [comment]
Thx @autumnfound - leave the header's as is.  

For the board pic, can you please add a title below the pic (not image hover) that reads "RISC-V dev board attendees will keep"

**Comment by autumnfound** [comment]
Is this what you're looking for?

Mobile/tablet:
![mobile/tablet view](https://user-images.githubusercontent.com/23018241/62890129-c8f2ea00-bd10-11e9-8df6-4ae918c188b6.png)
Desktop:
![desktop view](https://user-images.githubusercontent.com/23018241/62890158-dad48d00-bd10-11e9-94ef-979ac6977509.png)

**Comment by autumnfound** [comment]
This is live!
