### ISSUE TITLE
New Sponsor

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#37]
Hi @autumnfound - pls add Metrics as a sponsor.

[MetricsLogo_Final.eps.zip](https://github.com/openhwgroup/osdforum.org/files/3478992/MetricsLogo_Final.eps.zip)

![image](https://user-images.githubusercontent.com/2498391/62659680-084cbf80-b93a-11e9-8ce7-451dd0544dca.png)

**Comment by autumnfound** [comment]
This is live!
