### ISSUE TITLE
new sponsor logos

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#45]
@autumnfound pls add following new sponsors...

![fossi-foundation](https://user-images.githubusercontent.com/2498391/63377393-0af9dc80-c35e-11e9-9069-c50a67d58765.png)
- you already have the source for the above logo which is also on the openhwgroup.org site

![segger_logo_cmyk](https://user-images.githubusercontent.com/2498391/63377465-2f55b900-c35e-11e9-91fe-cb5c08610ca4.png)

[ieee master brand blue eps.eps.zip](https://github.com/openhwgroup/osdforum.org/files/3522250/ieee.master.brand.blue.eps.eps.zip)

**Comment by autumnfound** [comment]
Added new logos, they are now live! Fossi is small, this is due to the aspect ratio of the image
