### ISSUE TITLE
Create a osdforum logo

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/osdforum.org#5]
We need to create a logo for this new event site.

@rickoco I am assigning this to you since you are currently working with your Marketing agency for this.

**Comment by rickoco** [comment]
Ok - here's the logo..

![image](https://user-images.githubusercontent.com/2498391/62298808-b8ee2700-b441-11e9-8077-e25c0e0cd3f7.png)

Pls use it for the top left (header if you can - @stephanieswart can you create a white version?) and the footer (replacing the OpenHW Group logo).

**Comment by stephanieswart** [comment]
Hi Rick, do you have the vector version of the logo? Either an eps. svg. or ai file?

**Comment by rickoco** [comment]
sorry @stephanieswart - should have sent the vector file to begin with :-)

But I'll have to email it to you and Martin - no eps support in Github...

**Comment by chrisguindon** [comment]
@rickoco can you try zipping the files? Perhaps github support .zip?

**Comment by rickoco** [comment]
@stephanieswart @chrisguindon - zip eps attached...
[osdforum.eps.zip](https://github.com/openhwgroup/osdforum.org/files/3457322/osdforum.eps.zip)

**Comment by stephanieswart** [comment]
[osdforum_png_eps.zip](https://github.com/openhwgroup/osdforum.org/files/3457620/osdforum_png_eps.zip)
Here it is in white and I added black too in eps. and png. versions

**Comment by autumnfound** [comment]
This is now live! @rickoco how does that look?

**Comment by stephanieswart** [comment]
I think it looks great!

**Comment by rickoco** [comment]
Yes!  Looks awesome, thank you!  Nice work @stephanieswart and @autumnfound.  Now on to promoting, agenda and registration!!
