### ISSUE TITLE
Site down!

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#56]
@chrisguindon @autumnfound - guys OSDForum.org site is down...

**Comment by autumnfound** [comment]
Hey Rick, I can't reproduce at the moment. Could you check again please?

**Comment by rickoco** [comment]
Ya looks like the conference I’m at has blocked our site as a spamming url - I’ve asked why...

**Comment by rickoco** [comment]
Sorry for the false alarm :-(
