### ISSUE TITLE
last agenda tweak

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#61]
@autumnfound @chrisguindon - guys, sorry for this, but one last agenda tweak from the NXP speaker (3 deletions and add "SDK' to the 1:15pm talk)...

11:15am EDT ~~Hands-on:~~ Vega board SDK, open-isa.org and RV32M1 | Juan Carlos Pacheco (NXP)

1:15pm EDT | Hands-on: ~~Zephyr~~ SDK + IoT wireless connectivity using the Vega board | Juan Carlos Pacheco (NXP)

2pm EDT | Hands-on: Zephyr + MicroPython ~~+ Littlevgl~~ on the Vega board | Juan Carlos Pacheco (NXP)

**Comment by autumnfound** [comment]
this is live
