### ISSUE TITLE
slide & video links

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#63]
@chrisguindon @autumnfound - we have the slides and videos ready to go for posting on the OSDForum site.

Agenda spreadsheet with slides and videos links is here...
 [Agenda + Slide & Video Links​
](https://docs.google.com/spreadsheets/d/17LBqPV10D9bYF5wzLNny2XSLmvJCMKYI6C9aflp3SPs/edit?usp=sharing)

[Slides are located here](https://drive.google.com/open?id=18RcOITmTJfMXnYUZfvE-NC5Cy7EmlrXn), but please upload the PDFs for each talk instead of a link to GDrive as Gsuite is not accessible in all countries (China, etc.)
​
 Videos​
OSDForum [Youtube playlist with all the videos is located here](https://www.youtube.com/playlist?list=PL5xxtziB58VnpcYUIafJZHWFOIO8iFb8i)...

I leave on travel through the end of next week, so please reach out to Andrea (marketing firm) or Adam (video firm), on copy in the email I sent you, if you have any questions.

I'd appreciate if we could get the slide and video links up quickly.
Cheers,
Rick

**Comment by autumnfound** [comment]
Preview of what I'm thinking, WDYT?
![image](https://user-images.githubusercontent.com/23018241/65636791-02c23c00-dfb1-11e9-8b45-546d779b38d4.png)

Still WIP, should be done sometime tomorrow morning.

**Comment by autumnfound** [comment]
@rickoco I've created a PR and have a preview running of the agenda changes, but the panel slide deck is a whopping 25MB without compression. I've compressed it down to ~6MB by reducing the print quality, and can be seen at https://deploy-preview-64--osdforum.netlify.com/. Is that OK, and can we see about shrinking the size of these files? While we can host them, and it doesn't hurt overall page performance, they are quite large to download and can be quite slow.

**Comment by rickoco** [comment]
looks good @autumnfound - pls go ahead.  One small request would be to change VOD to Video as the header above the videos.  Thanks for getting these up quickly.

**Comment by rickoco** [comment]
@autumnfound @chrisguindon - guys, is this done?

**Comment by chrisguindon** [comment]
@rickoco Martin did an update to the PR this morning since he was off last Friday.

I was busy all day and I did not get a change to review the PR until now.
