### ISSUE TITLE
Homepage content update

### ISSUE THREAD

**Issue by shanda-eclipse** [openhwgroup/osdforum.org#69]
Please update the following content on https://www.osdforum.org/.

In Jumbotron, replace "Save the date September 15th, 2020" with "Virtual event | September 15th, 2020"

Under the about section:
Replace "The agenda also includes a hands on bring up session using a RISC-V based development board that attendees can keep." with  "The agenda also includes a hands-on session using a  CORE-V MCU open-source RISC-V core FPGA development board."

Replace "Made possible by the generous support of our sponsors, the OSDForum is a non-profit event with low attendee fees of $50 for industry attendees and $25 for academic attendees (includes the full day of talks, breaks, lunch and a RISC-V development board)." with "Made possible by the generous support of our sponsors, the OSDForum is a non-profit event with the low fee of $25 USD for industry and academic attendees. If you do not have a CORE-V MCU open-source RISC-V core FPGA development board, you can purchase one during the registration process at a discounted rate."

**Comment by ChristieWittEclipse** [comment]
![OSD-Forum-Header](https://user-images.githubusercontent.com/58480647/87325145-14081500-c4ff-11ea-80c0-0e73d1aa2807.png)
I've also attached a new header image that is not venue based, as the event is now virtual.

**Comment by shanda-eclipse** [comment]
@karenmcnaughton FYI
