### ISSUE TITLE
Homepage update (FPGA board)

### ISSUE THREAD

**Issue by hpollittsmith** [openhwgroup/osdforum.org#70]
Could you replace the current MCU board picture with a picture of the board we will be using this year:

![image](https://user-images.githubusercontent.com/17474197/87332229-474fa180-c509-11ea-8b31-df823c9d1195.png)

Also, please replace "CMC Microsystem" with "CMC Microsystems" on the line regarding co-hosts for the event.

Hugh

**Comment by annejacko** [comment]
Another request for the website. Could we change the text at the top to read this way:

<OSDForum logo>
Virtual Event | September 15, 2020
Save the Date

**Comment by autumnfound** [comment]
Currently, the homepage still references a RISC-V board given to attendees, should I remove that text for the time being?

**Comment by autumnfound** [comment]
@annejacko 
![image](https://user-images.githubusercontent.com/23018241/87567057-d4bdfd80-c691-11ea-876e-fded693409f6.png)

Looks a bit off...I'm thinking of shrinking the text a little to make it less, large I guess?

**Comment by hpollittsmith** [comment]
> Currently, the homepage still references a RISC-V board given to attendees, should I remove that text for the time being?

You could replace that text with:

The agenda also includes a hands-on session using a CORE-V MCU open-source RISC-V core FPGA development board, which attendees can purchase as an option with their registration.

**Comment by annejacko** [comment]
@autumnfound HI Martin -- let's remove the "th" after "15", make the text a bit smaller, and perhaps make the "Save the Date" text a big larger. I think that balance would be better.

**Comment by autumnfound** [comment]
@annejacko another request was made earlier to change that content (#69). I'll stick with that for the content, and we can change it if it is needed. 

@hpollittsmith turns out that our marketing folks already had a copy for that, so that will be updated in a separate PR!

**Comment by annejacko** [comment]
@autumnfound Please do NOT include the "th" even though Shanda included it. I'm sure it was an oversight on her part. It's wrong to use "th" in this context. Thanks!

**Comment by chrisguindon** [comment]
@annejacko I will remove the "th" in the jumbotron.
