### ISSUE TITLE
"Register Now" buttons

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#76]
please add "Register Now" buttons (one in the header image or just below under the event date and one at the top or bottom of the agenda section with the following link https://www.eventbrite.com/e/osdforum-2020-registration-112889000038

**Comment by autumnfound** [comment]
@rickoco We don't currently support content within the agenda block other than the agenda content. Did you want a new block afterward with the button and some text saying registration is open? If so, what content would you like?

**Comment by rickoco** [comment]
> @rickoco We don't currently support content within the agenda block other than the agenda content. Did you want a new block afterward with the button and some text saying registration is open? If so, what content would you like?

@autumnfound we're just looking to add "Register Now" buttons with the eventbrite registration link posted above.  So, if you could place 2 buttons, one in the header under the date and one just before the agenda, that would be great.
