### ISSUE TITLE
Sponsor logo display -- can we improve it?

### ISSUE THREAD

**Issue by annejacko** [openhwgroup/osdforum.org#90]
Right now on the OSDForum site, when you view the page on a full-size monitor, the logos look small, and the arrangement isn't balanced. See the screen shot with one logo on the second line, and all the others on the first line.

https://www.osdforum.org/

Ideally, the logos would be larger or with less white space, and be balanced in the way they are displayed (and responsive to different screen sizes.

Is this something we can update now? Thanks!
![Screen Shot 2020-09-09 at 5 14 04 PM](https://user-images.githubusercontent.com/29178654/92667111-e30a4d80-f2bf-11ea-9849-ca7177081a50.png)

**Comment by rickoco** [comment]
Any progress here?

**Comment by chrisguindon** [comment]
@autumnfound can you take a look at this on monday?

**Comment by autumnfound** [comment]
@annejacko @rickoco please see the following preview for a suggested fix: https://deploy-preview-95--eclipsefdn-osdforum.netlify.app/

I upped the width of the logos somewhat so that more of them flow to the next row to look more natural without being too large. WDYT?

**Comment by annejacko** [comment]
Thanks, Martin. Better! But on a 27" monitor, it's still pretty lopsided -- two logos are now on the second line. Would a slight increase to the size put three of them on the second line? That would look even better. A slightly larger size would also be consistent with the size of the organizer logos above, so I think that could work.

**Comment by autumnfound** [comment]
Looks like a discrepancy between my branch and the master somehow? On my local copy, there were three in the bottom row. I've upped it a little to reflect that. On the difference in size, there are no differences, just the appearance of one. The organizer logos are the same size, and just look bigger as there are more square logos (which benefit from the way we equalize the logos).

**Comment by annejacko** [comment]
Just clicked on the link you provided and I see three on the second line now. Much better. The right way to do this is to ask the sponsors for logos with certain sizes and proportions, which is what we do for EclipseCon. Note for the future! :-)

My take is that we should deploy this... I have pinged Rick for him to review.
