### ISSUE TITLE
Slides and Videos

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/osdforum.org#97]
Pls post the PDFs and links to Videos for each of the talks shown on the agenda https://www.osdforum.org/ (11 talks with slides & videos).  Note, there are no slides or video for the 9am talk.  Slide PDFs are in the archive linked here [https://drive.google.com/file/d/1uPJM8ciABbuQ5pxfnCDF4WoITBfCP-of/view?usp=drivesdk and video urls are shown below in chronological order.  Also, the chronological video playlist is shown here https://www.youtube.com/playlist?list=PL5xxtziB58VlMEtfCjIcd2mN-Shq5qE93

1 https://youtu.be/_D-ZUeqd4Hs
2 https://youtu.be/3XKzTjNyHT8
3 https://youtu.be/C3k8z9nMvII
4 https://youtu.be/jPS3Urqmd4Q
5 https://youtu.be/dxO72R-dBWk
6A https://youtu.be/b_rWumk3Fic
6B https://youtu.be/xG-5XMfdYIQ
6C https://youtu.be/8nQjKbpejZo 
7 https://youtu.be/PeGBvAe0yHw
8 https://youtu.be/AOQ50uhhqSc
9 https://youtu.be/0hiCYSOK-ac

**Comment by chrisguindon** [comment]
@flora8984461 This is something we would like to get done before EOD tomorrow! 

Thanks!
